---
title: Casey Gollan
url: http://caseyagollan.com
timezone: UTC
gems:
  - jekyll-redirect-from
collections:
  notebooks:
    title: Notebooks
    output: true
  posts:
    title: Posts
    output: true
  things:
    title: Things
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: notebooks
  values:
    layout: notebook
permalink: pretty
