---
title: Casey Gollan
url: http://caseyagollan.com
timezone: UTC
collections:
  notebooks:
    title: Notebooks
    output: true
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  things:
    title: Things
    output: true
  work:
    title: Work
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
defaults:
  - scope:
      path: ""
      type: notebooks
    values:
      layout: notebook
permalink: pretty