---
title: Casey Gollan
timezone: UTC
collections:
  notebooks:
    title: Notebooks
    output: true
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  things:
    title: Things
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: notebooks
  values:
    layout: notebook
gems:
- jekyll-redirect-from
permalink: pretty
